### ISSUE TITLE
canvas之乱线抽象画

### ISSUE THREAD

**Issue by domsgit** [domsgit/blog#15]
基本结构：
```html
<canvas id="canvas">
 你的浏览器不支持 canvas，请升级你的浏览器。
</canvas>
```

```css
html,body {
  margin: 0;
  padding: 0;
  height: 100%;
  overflow: hidden;
}
#canvas {
  display: block;
}
```

```js
main()

function main() {
  var cvs = document.getElementById('canvas')
  var width = document.documentElement.clientWidth
  var height = document.documentElement.clientHeight

  if(!cvs.getContext) return
  cvs.width = width
  cvs.height = height
  var ctx = cvs.getContext('2d')

  for(let i = 0; i < 50; i++) {
    ctx.beginPath()
    ctx.lineWidth = Math.floor(Math.random() * 6)
    ctx.strokeStyle = randomHexColor()
    ctx.moveTo(~~(width * Math.random()), ~~(height * Math.random()))
    ctx.lineTo(~~(width * Math.random()), ~~(height * Math.random()))
    ctx.stroke()
  }
}

// https://gist.github.com/domsgit/e56f5a92197e14753d13bce42a10ea1f
function randomHexColor() {
  return '#' + (~~(Math.random() * (1 << 24))).toString(16)
}
```
