### ISSUE TITLE
canvas之平行线抽象画

### ISSUE THREAD

**Issue by domsgit** [domsgit/blog#16]
```html
<canvas id="canvas">
 你的浏览器不支持 canvas，请升级你的浏览器。
</canvas>
```

```css
html,body {
  margin: 0;
  padding: 0;
  height: 100%;
  overflow: hidden;
}
#canvas {
  display: block;
}
```

```js
main()

function main() {
  var cvs = document.getElementById('canvas')
  var width = document.documentElement.clientWidth
  var height = document.documentElement.clientHeight

  if(!cvs.getContext) return
  cvs.width = width
  cvs.height = height
  var ctx = cvs.getContext('2d')

  var angle = Math.random() * Math.PI

  for(let i = 0; i < 100; i++) {
    ctx.beginPath()
    ctx.lineWidth = Math.floor(Math.random() * 6)
    ctx.strokeStyle = randomHexColor()
    var sx = width * Math.random()
    var sy = height * Math.random()
    ctx.moveTo(sx, sy)
    var length = Math.random() * 50 + 10
    ctx.lineTo(sx + length * Math.cos(angle), sy + length * Math.sin(angle))
    ctx.stroke()
  }
}

function randomHexColor() {
  return '#' + (~~(Math.random() * (1 << 24))).toString(16)
}
```
