### ISSUE TITLE
docker相关

### ISSUE THREAD

**Issue by domsgit** [domsgit/blog#29]
# docker

[docker官网](https://www.docker.com/)

[docker中文官网](https://docs.docker-cn.com/)

[Docker 问答录（100 问）](https://blog.lab99.org/post/docker-2016-07-14-faq.html#docker-yin-qing-xiang-guan-wen-ti-67)

[Docker — 从入门到实践](https://yeasy.gitbooks.io/docker_practice/content/)

[Docker 17.09 官方文档中文笔记](https://docs-cn.docker.octowhale.com/)

## 一、node

[node的官方docker镜像](https://hub.docker.com/_/node/)

拉镜像仓库：

```bash
docker pull node
```

启动node容器：

```bash
# 第一个node是给容器起的别名，第二个node是镜像名，第三个node是在bash中运行node命令
docker run -it --rm --name node node node
```

## 二、搭建npm私有仓库

[verdaccio/verdaccio](https://verdaccio.org/)

#### 1.1 创建配置文件

```bash
mkdir -p /home/docker/verdaccio
git clone https://github.com/verdaccio/docker-examples
mv docker-examples/docker-local-storage-volume /home/docker/verdaccio
```

1.2 修改配置文件

1.2.1 修改 `conf/config.yaml`

```bash
# 使用淘宝的cnpmjs镜像，加速
uplinks:
  npmjs:
    url: https://registry.npm.taobao.org/
```

1.2.2 修改 `conf/htpasswd`

到 [http://tool.oschina.net/htpasswd](http://tool.oschina.net/htpasswd) 生成需要的账号密码

1.2.3 删除 `/home/docker/verdaccio/storage` 下面的文件

#### 1.2 创建并运行容器：

```bash
docker run --name verdaccio -d -v /home/docker/verdaccio:/verdaccio -p 4873:4873 verdaccio/verdaccio:latest
```

1.2.1 通过 docker logs verdaccio 查看日志发现存在权限问题，是由于使用了挂载的数据卷和容器内部的权限不一致的问题，需要修改下权限：

1.2.1.1 进入容器

```bash
docker exec -it verdaccio sh
```

1.2.1.2 查看用户ID

```bash
whoami & id
```

#### 2.1 查看私有npm有哪些包：

浏览器上访问 `http://xx.xx.xx.xx:4873`，查看私有仓库上有哪些包

#### 2.2 下载私有包

npm全局安装nrm：

```bash
npm i -g nrm
```

给npm添加私有仓库源：

```bash
nrm add sinopia http://xx.xx.xx.xx:4873
```

假如有一名为`yoyosys-test`的包，下载该包，方式如下：

```bash
nrm use sinopia
npm i yoyosys-test
```

#### 2.3 新建私有包

添加私有npm仓库用户名：

```bash
npm login --registry=http://xx.xx.xx.xx:4873
```

在新建包的根目录下publish该新建的包：

```bash
npm publish --registry=http://xx.xx.xx.xx:4873
```

## 三、[wordpress](https://cn.wordpress.org/)

[wordpress docker](https://hub.docker.com/_/wordpress?tab=description)

新建一个文件`wordpress`文件夹，在文件夹里新建一个名叫`docker-compose.yml`的文件，内容如下：

```
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
```

然后在终端执行：

```bash
docker-compose up -d
```

## 四、ionic

[agileek/ionic-framework](https://hub.docker.com/r/agileek/ionic-framework/)

## 五、[mongo-express](https://github.com/mongo-express/mongo-express)

[mongo-express](https://hub.docker.com/_/mongo-express/)

## 六、jenkins

[jenkins](https://hub.docker.com/_/jenkins/)

## 七、[swagger](http://swagger.io)

[swaggerapi/swagger-editor](https://hub.docker.com/r/swaggerapi/swagger-editor/)

### 3. 参考链接

[告诉你为何以及如何搭建一个私有的npm仓库](https://www.colabug.com/2731929.html)
