### ISSUE TITLE
threejs之画线

### ISSUE THREAD

**Issue by domsgit** [domsgit/blog#6]
```css
html, body{
    margin: 0;
    padding: 0;
}
canvas {
    width: 100%;
    height: 100%;
}
```
```js
var height = window.innerHeight
var width = window.innerWidth

var scene = new THREE.Scene()

var renderer = new THREE.WebGLRenderer(45,width/height,1,500)
renderer.setSize(width, height)
document.body.appendChild(renderer.domElement)

var camera = new THREE.PerspectiveCamera()
camera.position.set(0,0,100)
camera.lookAt(0,0,0)

var geometry = new THREE.Geometry()
var material = new THREE.LineBasicMaterial({color: 0xff0000})
geometry.vertices.push(new THREE.Vector3(-10,0,0))
geometry.vertices.push(new THREE.Vector3(0,10,0))
geometry.vertices.push(new THREE.Vector3(10,0,0))
var line = new THREE.Line(geometry, material)
scene.add(line)

renderer.render(scene, camera)
```
