### ISSUE TITLE
threejs之创建文字

### ISSUE THREAD

**Issue by domsgit** [domsgit/blog#8]
```css
.dom-css-text {
  position: absolute;
  top: calc(50% - 5rem);
  left: calc(50% - 5rem);
  width: 10rem;
  height: 10rem;
  background: rgba(255, 0, 0, 0.5);
  border: 0.1rem solid red;
}
```

```html
<div class="dom-css-text">dom + css text</div>
```
